### ISSUE TITLE
ignore help of subcommands

### ISSUE THREAD

**Issue by Miezhiko** [bfgroup/Lyra#63]
I have sub-commands with own arguments and I see them if I do `app foo --help`

but I don't want to see those when I type `foo --help` I only want to see that sub-command itself exists, is it currently possible to do?

**Comment by ljusten** [comment]
+1 the help gets very messy if there are lots of subcommands. The Go package Cobra only shows the command and a short description, similar to what op suggests, e.g.

Available Commands:
  cmd1      Runs cmd1
  cmd2      Runs cmd2
